### ISSUE TITLE
Se despliega una ventana que no es requerida

### ISSUE THREAD

**Issue by pauriveraa** [OscarLopera/sofka-okr-front-git#17]
**Desarrollador de la funcionalidad:**
@stephany-rivera 

**Dónde:** 
https://sofka-okr-front-deploy.web.app/dashboard

**Cuándo:**
1. Autenticarse correctamente.
2. Click en Calendario.
3. Click en Dashboard
4. Click en la opción Todos dentro de Dashboard.

**Defecto:** 
Al seguir el flujo descrito anteriormente me vuelve a mostrar una ventana emergente con un mensaje de bienvenida a la aplicación.

![Dashboard-Todas](https://user-images.githubusercontent.com/62780717/116608781-35ed4f80-a8f9-11eb-9c63-47aa4f8442f1.PNG)

**Esperado:** 
Lo esperado es que no se muestre esta ventana emergente y si que persistan la columna del menú, la barra superior y el body en blando de la opción (Todos).

**Comment by stephany-rivera** [comment]
@pauriveraa Esta notificación no nos corresponde a nosotros y esta ventana esta planteada en las hu de los de notificaciones.

**Comment by pauriveraa** [comment]
Listo, Stephany!
@stephany-rivera
