### ISSUE TITLE
Titulo de aplicativo no es un botón

### ISSUE THREAD

**Issue by pauriveraa** [OscarLopera/sofka-okr-front-git#19]
**Desarrollador de la funcionalidad:**
@stephany-rivera 

**Dónde:** 
https://sofka-okr-front-deploy.web.app/dashboard

**Cuándo:**
1. Autenticarse correctamente.
2. Click en Calendario.
3. Click en titulo SOFKAOKR de la barra superior.

**Defecto:** 
Al seguir el flujo descrito se evidencia que el titulo es un elemento en el que se puede dar click y esto no está plantado en los CA, esto se presenta en varias flujos diferentes, es decir, si doy click en cualquier opción del menú y después le doy click en el titulo, de sespliega la ventana de bienvenidos.

![Dashboard-Title](https://user-images.githubusercontent.com/62780717/116616991-f592cf00-a902-11eb-92ea-fa41b0220f5b.PNG)

![Dashoard-Title-2](https://user-images.githubusercontent.com/62780717/116617484-7e116f80-a903-11eb-80fa-e2c800672143.PNG)

**Esperado:** 
Lo esperado es que ese solo sea un titulo, no se le debe implementar una función adicional.

**Comment by stephany-rivera** [comment]
@pauriveraa  pendiente de realizar cambios.

**Comment by pauriveraa** [comment]
El PO Daniel Zuluaga confirma que el botón si tiene la funcionalidad de volver al home de dashboard (en este caso a las OKRs personales), y que hacía falta agregarlo a las HU. 
@stephany-rivera
