### ISSUE TITLE
No se evidencia comportamiento de avance en Burndown chat

### ISSUE THREAD

**Issue by DannySofka** [OscarLopera/sofka-okr-front-git#28]
## Cuándo: 

1. Selecciono el botón de Login desde el Home: https://sofka-okr-front-deploy.web.app/
2. Ingreso correo electrónico y contraseña válidos
3. Visualizo la gráfica Burndown chat

## Defecto: Solo está mostrando la línea de Avance esperado, pero no es posible comprobar comportamiento real del avance actual.
![image](https://user-images.githubusercontent.com/78866985/116704880-87e1b400-a991-11eb-9e36-cf6f400201b2.png)

## FRONTEND

**Comment by sebastianpg12** [comment]
Se corrigió esto, debido a que no aparecia un avance por que el okr registrado no tenia un avance, pero ya hay un okr con un avance para que se evidencie

**Comment by DannyQA08** [comment]
Se realizan de nuevo pruebas a la funcionalidad la cuál ahora se encuentra operativa. Se procede con el cierre del Issue.

![image](https://user-images.githubusercontent.com/78866985/116733743-182ff100-a9b2-11eb-93c8-2ce068fa6e52.png)
