### ISSUE TITLE
Opción "Edit" en tabla de características generales sin acción programada

### ISSUE THREAD

**Issue by DannySofka** [OscarLopera/sofka-okr-front-git#30]
## Cuándo: 

1. Selecciono el botón de Login desde el Home: https://sofka-okr-front-deploy.web.app/
2. Ingreso correo electrónico y contraseña válidos
3. Podré visualizar tabla con características generales del OKR

## Defecto: Aparece Texto que dice "Edit" el cuál no está cumpliendo ninguna acción

![image](https://user-images.githubusercontent.com/78866985/116712464-7f8d7700-a999-11eb-997d-9a4a4a84dead.png)

## Front

**Comment by andreasuarezc** [comment]
El texto Edit no corresponde a un atributo contemplado para la tabla de OKr, este texto se encuentra allí por error, pero no pudo ser eliminado ya que el tiempo para hacer el último commit ya había pasado. 

Se tendrá en cuentra la solución de este error en un próximo Sprint.

**Comment by DannyQA08** [comment]
Se cierra Issue de acuerdo a los comentarios realizados por la desarrolladora Andrea Suarez donde explica que el bug será corregido en el próximo Sprint
