### ISSUE TITLE
Hallazgo en Page inicio de sesión

### ISSUE THREAD

**Issue by pauriveraa** [OscarLopera/sofka-okr-front-git#8]
**Desarrollador de la funcionalidad**: @juanfelipejg 
**Dónde**: https://sofka-okr-front.web.app/ 
**Cuándo:** se ingresa en la ruta del aplicativo entonces visualiza el page de inicio de sesión
**Defecto:** En el page de iniciar sesión se visualizan un titulo (sofka y sofka U), una opción para desplegar un menú, las opciones sign in y sign out que no están incluidas en el criterio de aceptación de este page.
![Elementos pagina de inicio](https://user-images.githubusercontent.com/62780717/116407571-841a2a00-a7f7-11eb-8a94-deffa50c4a45.PNG)

**Esperado:**  el titulo con el nombre del aplicativo (Sofka OKR) tentativamente, el logo de sofka, el botón de google para inicio de sesión con google, una breve descripción de nosotros y algunas fotos relacionadas con sofka.  

**(Frontend)**

**Comment by stephany-rivera** [comment]
@pauriveraa solucionado
